{% set name = "aipy" %}
{% set version = "2.1.5" %}
{% set sha256 = "a597d726f61e6cd3b64ac951d37af473a8e1d6648fdafbc3a81dfe8c82257679" %}

package:
  name: {{ name }}
  version: "{{ version }}"

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=files.txt
  skip: true  # [win or py3k]

requirements:
  build:
    - toolchain
    - astropy >=2.0
    - ephem
    - numpy >=1.11
    - python <3
    - setuptools

  run:
    - astropy >=2.0
    - ephem
    - numpy >=1.11
    - python <3

test:
  imports:
    - aipy
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PRFIX $PKG_NAME  # [osx]

about:
  home: https://github.com/HERA-Team/aipy
  license: GPL v2+
  license_family: GPL
  license_file: LICENSE
  summary: 'Astronomical interferometry in Python'

extra:
  recipe-maintainers:
    - pkgw
