{% set name = "aipy" %}
{% set version = "3.0.5" %}
{% set sha256 = "950da37add39be46a21e830f1edbdaabc109aa9f1ca2ac686c825a8e7a142c23" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python
    - pip
    - numpy

  run:
    - astropy >=2.0
    - ephem
    - healpy >=1.11
    - {{ pin_compatible('numpy') }}
    - scipy >=0.19
    - python

test:
  imports:
    - aipy
    - aipy._deconv
    - aipy._dsp
    - aipy._miriad
    - aipy.utils
  commands:

about:
  home: https://github.com/HERA-Team/aipy
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Astronomical interferometry in Python

extra:
  recipe-maintainers:
    - pkgw
