{% set name = "aipy" %}
{% set version = "3.0.0rc1" %}
{% set sha256 = "16601f07d559c8e968cbbc35cc09fe11341f6054b7011e1c3e9611832ccc051f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python
    - pip
    - numpy

  run:
    - astropy >=2.0
    - ephem
    - healpy >=1.11
    - {{ pin_compatible('numpy') }}
    - scipy >=0.19
    - python

test:
  imports:
    - aipy
    - aipy._deconv
    - aipy._dsp
    - aipy._miriad
    - aipy.utils
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PRFIX $PKG_NAME  # [osx]

about:
  home: https://github.com/HERA-Team/aipy
  license: GPL v2+
  license_family: GPL
  license_file: LICENSE
  summary: 'Astronomical interferometry in Python'

extra:
  recipe-maintainers:
    - pkgw
