travis:
  secure:
    BINSTAR_TOKEN: JmlRw49e+4uGKszoitX+OXjq/Da4C5Nm4D7UHkVuwNUgpxmO5e979W8BIpmsqtch67HbjxmpD6E8qigWDygum28js4R2D2H/U3QXM0FnJQTodAZJ0xkbylogGlYJ8Nhk5kQzVJNO0eoEVYdmrh7Xxh9tt9FSnQPQyadXYJcWMf1hsbyfR5mqvPJWSPhZllqVmtX8iECVO8aP+xKNumevK8xVizBsv5tjUoU/zAqI9WbKYDuNtd3APB5zYKneD2kMd8rNpdClbdOKz1ae7UVD4SE6nSsZ7dVfZN2gBZ0YM6y6SHk3ri8TC5IrX84c/XtEXH4/0rHAf/QRE2b0DMCg8QG0ruLNUUbOkaMRkWTbrKN/jisGbnkIqjx6ma3fPHHXd/WTeobmdyOwes4Bb1v67l5KK55OXu19416tsvDLlQFD542Z7U2vKaRdiDEVAgtNxlLKT8s3bfVRSZm+0rakfEjqqPAE5OHDn/k4QlAM1tuTccHh/uQB2yzP2Q93IrxreozsgKzD7pbUhDj9UkjZ9/4xZOglTVqzBUQCRwHF2ziN2DSIwQbj0cVMTWSzKxbnRti6464WKwZZC7qScLh7P3Q7TC9jw0XXcjw/sjJfBGxNv/IJwD7Joh1x3bAp3dnDv+E/48Cc8XpKJUb+C6vpq/VT7E7VWiSHW+EsqiiYTR4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
