travis:
  secure:
    BINSTAR_TOKEN: lummuf279lPAz6TaaQ5GOCCt7ioGczz1glutfQrrni1GC6mYQ2qvAQTIcVeVI8hJVzgqb83Vd9Hs+vtUEnb3L43Dfm9ia/U0Y+5wnXHwClFw3Ob6HqK7/Z9JHaFkbkAnFBz+zavGui3vn7Gby9Q5GEeLsgar0VkA5Pph0vAQu5kffB/fvwcHj89joi31vM1X2IEROUbMvZFZKfkJhqhsJZsZh595nDXMd3GZiQsyvjaRgYJIr213KjPWHQ9PpS/KDmA5EXtXcg+WY+lSENV9pWFBu+WCqT0IgS7iKmxLKY9af59Gv3B8Z57RuLiWOOfLrKTGWDAuy26uP7kYS1CwtkruJV1x0EXhq0K0+qkhKnM46mUpEzA679iE/Uq+IHsv7V1HmY+Uz3payCnANy7v7wuAk5bEgrQdjPjKI7/+tGg1d+83KHT96DcDW863vQVF3fhZMpJkVlkTHsqY0rPOMH3io6SIrm5xBJtXzxkKCxJOFXSNk0Stz7ariSm9uF/+STOTTSoQF3UyWVi1Kv9/IphCedCiGJeLS9IbYix+P62F8KwKmtWsJnehKZghpK6EK8vqXt+UFQtFo1UdsGWdtWPdBUAxIo+5mxO57deStKWWvMjV/2ISd9IAa0RtCuC2ByCrGIDejrF1TjavI+1KRRxjGw2j5xBQOzxgScz4z4A=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
