appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: bCKqlS/lA0unhb4EsT6xkmWE7/h89/fnyucgaauFqcmpChsgcpsVkeIEpV8To1k8bJ01NPVbk6EMAFEPlkc9J3GGauW0tgE9c73oQrp8WFZRe6CPeKs5xCTxttktoqZSqyCgrahPSuNkwToTaDOr8WnkmX6UbeQ7bheo4mgePqcJXDGIdZhRXASDArXTrerMngCy/WgQPmmHBJyTKvZ+EzONGpMXL9BeZV60FTXo5OuIsN/aADC5mExQhbqSf/STRyJaoTd26nfZgZkzcilLlXmcP/qsp1VWHCPPGTIthdazNugNQk7vP7qmfb8lXI1p+aEcFs8S3MNk34EX7zY9hGoLfEz3+PfdurpUVo+aVUIEOd5j+G4jDWla/LLHlXFS9ENHyasDFzMRP7ZlrtwNviixs+qiOD7lPImv0AHwER806RpcAHx7vHDeohkG6E8TwRATe9PR5OFBkStcYA2YIMji5XPDVuFBpGWWfNFUqi2RWRJrq8l7PQyBkuxFJn1sEStq6RmuhckOO52nSWG/qfYbp8j6b29ggCxOldnLKp/ZWiXe1XorEVeOl9CnEXvcKo7xZ6doLgqrz+1gL0wMRKRIMApfwGkXsN6DvfdZgui+sCwIBfxLionzHX0Z1jw4FWWIuFf+BMzbnhAilKQtKTX+tfxBDGqxZXWUH1Wn5W0=}
conda_forge_output_validation: false
