travis:
  secure:
    BINSTAR_TOKEN: CEJFjMLOxkgFl/9nXoKDjZ7g98WE13xc4nXf66TcAz8TxNRrM4/7tZBUmK88tVEN5+XFtURAgKigowNYi3Kf9q8B6lICTCo27y83fDI/QsREO6hmSvPpygNC29LzBfQBOPLZprpHRSeiWERmM6qXuqrplvlvjnK6++UWXdZiNEDcnr7HUkTDOhtfV8gbw6JrOGf7L+51vNvlR70LXt1b+g0Zzbe9RUaGE7+pmESUyRO98E9HCNQV77ly3JttICLXmtBVPXQtEHjrSiF8RzsYd8hOfqDGbiVLZAh1rQlwCQk09Dxpe+gbrBw2x3Ai9tHv0CHGk2h/Ql5TNLN5FknVNiN2CjlfHMoBvPacTxcYlT2Q1cjNihJcPMCgatskVfR5uzVS3icHAxxWVo4wyVX8UY7CiQPMwolPrNJlDpIrq6Fv1zziZsMcRJwKWkRMLf6JmD9QiHIK7Dz6qkLsXZ2GllIUgzCcCq9ceT4iRkqd97HLKJyVr4vFySZ/N7QIz7s562DcmO/+z/SIokR/44I++hQ6Z9gE/PhfhbzxHpnt3TjpJrEo/MJgOSQYeiXAsjHQwB+smhO2Ydqm5zXVlUVzl1sOyAC5huaVuKbBitb1ANgcppFkdES4Cclka2A0h/Lv4++QDaWqgsGcNuPYH2lDGjhK6gtnyb51atz269pXFxw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
